[package]
name = "map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]
name = "map"

[dependencies]
poisson = { path = "../poisson" }
thiserror = "*"
rand = { version = "0.8.4" }
