[tasks.copy-assets]
script = '''
mkdir -p ../web/public/logic/assets && cp -R assets/* ../web/public/logic/assets/
'''

[tasks.compile-wasm]
command = "wasm-pack"
args = ["build", "--release", "--target", "web", "-d", "../web/public/pkg"]

[tasks.web]
dependencies = [
    "copy-assets",
    "compile-wasm"
]
