[tasks.copy-assets]
script = '''
cp -R assets ../web/public/
'''

[tasks.compile-wasm]
command = "wasm-pack"
args = ["build", "--release", "--target", "web", "-d", "../web/public/pkg"]

[tasks.web]
dependencies = ["copy-assets", "compile-wasm"]
